prompt --application/deployment/install/install_installlaptoprequeststable
begin
--   Manifest
--     INSTALL: INSTALL-InstallLaptopRequestsTable
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>2200437608860210
,p_default_application_id=>101
,p_default_id_offset=>2202822233886717
,p_default_owner=>'CICD'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(1526542736508103090)
,p_install_id=>wwv_flow_imp.id(1266119789670636890)
,p_name=>'InstallLaptopRequestsTable'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'  CREATE TABLE "EBA_DEMO_APPR_LAPTOP_REQUESTS" ',
'   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, ',
'	"EMPNO" NUMBER NOT NULL ENABLE, ',
'	"STATUS" VARCHAR2(16) DEFAULT ''PENDING'' NOT NULL ENABLE, ',
'	"DECISION_DATE" DATE, ',
'	"APPROVER" VARCHAR2(80), ',
'	"APPROVAL_TASK_ID" NUMBER, ',
'	"WORKFLOW_ID" NUMBER, ',
'	"LAPTOP_TYPE" VARCHAR2(10), ',
'	"NEED_BY" DATE, ',
'	"ORDER_DATE" DATE, ',
'    "ORDER_ID" NUMBER(10,0),',
'	"DELIVERED_DATE" DATE, ',
'	"DELIVERY_ACTION_TASK_ID" NUMBER, ',
'	 CONSTRAINT "LAPTOP_REQUEST_STATUS_CK" CHECK (status IN (''APPROVED'',''REJECTED'',''PENDING'', ''DELIVERED'')) ENABLE',
'   )  ROWDEPENDENCIES ;'))
);
wwv_flow_imp.component_end;
end;
/
